### ISSUE TITLE
External Data

### ISSUE THREAD

**Issue by mahmutoktay** [thanhnguyennguyen/trading-indicator#40]
Is it possible to add candle data externally?

**Comment by WildChildForLife** [comment]
Good question, if I could use my own data et extract different technical indicators, that could be awesome and avoid to be banned from Binance for multiple async / await calls for my live stream.

**Comment by WildChildForLife** [comment]
Got it, for that I had to use directly this package instead https://www.npmjs.com/package/technicalindicators which takes data as input and calculate the technical indicators.
