### ISSUE TITLE
Alerts Golden cross / Death cross

### ISSUE THREAD

**Issue by pageofthailand** [thanhnguyennguyen/trading-indicator#47]
How to Alerts Golden cross / Death cross when **Once per bar close** 
same as tradingview.com

Thank you.

**Comment by thanhnguyennguyen** [comment]
https://github.com/thanhnguyennguyen/trading-indicator/blob/master/README.md#golden-cross--death-cross

**Comment by pageofthailand** [comment]
How to alert when bar close.
