### ISSUE TITLE
Alerts moved?

### ISSUE THREAD

**Issue by kenchambers** [thanhnguyennguyen/trading-indicator#49]
Greetings!

Excellent library btw. 

for your ema cross I don't see alerts being exported from main module.

```js
  alerts = require('trading-indicator').alerts

  await alerts.priceCrossSMA(14, 'binance', 'BTC/USDT', '1h', false) 
  //Test SMA cross
  // { cross: true, direction: 'up' }


  await alerts.priceCrossEMA(14, 'binance', 'BTC/USDT', '1h', false) 
  // Test EMA cross
  // { cross: true, direction: 'down' }
  
```

Alerts here is returning `undefined`

I do see priceCrossEma on `require('trading-indicator')`

but when i try to use it , says `ema is missing`

**Comment by thanhnguyennguyen** [comment]
fixed in #48 
PLease update to v1.0.7
https://www.npmjs.com/package/trading-indicator/v/1.0.7
