### ISSUE TITLE
TypeError: Cannot read property 'rsicheck' of undefined

### ISSUE THREAD

**Issue by yaelahrip** [thanhnguyennguyen/trading-indicator#50]
TypeError: Cannot read property 'rsicheck' of undefined

did i miss something ? and how to fix this ?

thanks

**Comment by yaelahrip** [comment]
I fixed this :

const tradindi = require('trading-indicator')
 let rsiNow = await tradindi.rsiCheck(10, rsi_obought, rsi_osold, 'binance', 'BNB/USDT', '5m', false);

**Comment by papegaill** [comment]
Thanks for the info @yaelahrip, I think a PR should be opened to fix the readme in this case?
